{
  "comments": [
    {
      "key": {
        "uuid": "f7ac2b06_cf3f2d47",
        "filename": "src/onaptests/configuration/basic_network_nomulticloud_settings.py",
        "patchSetId": 8
      },
      "lineNbr": 24,
      "author": {
        "id": 5622
      },
      "writtenOn": "2020-10-16T06:55:38Z",
      "side": 1,
      "message": "I would suggest to add a TestConfigurationException as in basic_vm",
      "revId": "6b050f0ad7b04e8b0ffd035d5715032d95e020b0",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d247dfe0_4402cd96",
        "filename": "src/onaptests/scenario/basic_network.py",
        "patchSetId": 8
      },
      "lineNbr": 49,
      "author": {
        "id": 5622
      },
      "writtenOn": "2020-10-16T06:55:38Z",
      "side": 1,
      "message": "Some exceptions are missing:\nServiceInstantiateException\nServiceCleanupException",
      "revId": "6b050f0ad7b04e8b0ffd035d5715032d95e020b0",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "9385df87_f204d061",
        "filename": "src/onaptests/steps/instantiate/vl_ala_carte.py",
        "patchSetId": 8
      },
      "lineNbr": 141,
      "author": {
        "id": 5622
      },
      "writtenOn": "2020-10-16T06:55:38Z",
      "side": 1,
      "message": "Where is the exception?",
      "revId": "6b050f0ad7b04e8b0ffd035d5715032d95e020b0",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}