{
  "comments": [
    {
      "key": {
        "uuid": "7657d56c_9d67e353",
        "filename": "src/onaptests/utils/exceptions.py",
        "patchSetId": 1
      },
      "lineNbr": 11,
      "author": {
        "id": 1215
      },
      "writtenOn": "2020-12-01T17:07:29Z",
      "side": 0,
      "message": "you could have replaced the name :)",
      "revId": "a6fe8be6c1d1eb9e7293ed1c3bb63a76646fe22c",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}